### PR TITLE
update version 3.5.6 and cljsjs/firebase

### PR DESCRIPTION
**Pull request by jojoucsd**

### CODE REVIEW

**Comment by pdelfino** [comment]
Nice. LGTM

After merging this, it will be necessary to update everything consuming this library, including the CI build:

https://github.com/tallyfor/balance/blob/78aafefc76a7b8921d1b1ed9907921c105fa67d4/.github/workflows/ci.yml#L281

**Review by pdelfino — APPROVED** [review]

**Comment by pdelfino** [comment]
I added label, assignment, and project for the Project manager effort with GitHub projects

**Comment by benzenwen** [comment]
I love the completeness, but matchbox is NOT a balance dependency.  I'm going to open a new issue to review all ci.yml dependencies with an eye to removing unnecessary dependencies.  matchbox is only a voyage dependency, hence, we shouldn't touch the cljsjs/firebase dependency.  This is one of those "don't touch the mainframe" examples.

**Comment by jojoucsd** [comment]
In this case we should separate the CI check from Balance and Voyage. (remove the match box from the ci on balance and others that are not require to build balance) The whole reason for updating and this PR is because balance CI check throws error for matchbox version are out of sync. This gives a false impressions that the PR is not up to dated.

**Comment by jojoucsd** [comment]
closing this PR as Ben mentioned "don't touch the mainframe" example.

**Pull request closed without merging**
